### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by Psyga315** [Malven31/foundryVTT-SWFFG-status-automation#2]
Error: The FFG Star Wars Status Automation module does not provide a download URL that can be installed
    at Module.installPackage (file:///C:/Program%20Files/Foundry%20Virtual%20Tabletop/resources/app/dist/packages/views.mjs:1:3003)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async SetupView.handlePost (file:///C:/Program%20Files/Foundry%20Virtual%20Tabletop/resources/app/dist/server/views/setup.mjs:1:2113)
fetch @ foundry.js:72076
setup.js:7683 Uncaught (in promise) Error: The FFG Star Wars Status Automation module does not provide a download URL that can be installed
    at Module.installPackage (file:///C:/Program%20Files/Foundry%20Virtual%20Tabletop/resources/app/dist/packages/views.mjs:1:3003)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async SetupView.handlePost (file:///C:/Program%20Files/Foundry%20Virtual%20Tabletop/resources/app/dist/server/views/setup.mjs:1:2113)

**Comment by Malven31** [comment]
Thanks for the report, investigation on it's way.
It's my first release ever on foundry, it's likely I've made a mistake on the links I gave to foundry or something like that... sorry for the trouble !

**Comment by Malven31** [comment]
Version `0.1.6` is now downloadable and works as intended. Which is, for now, a very small feature.
I had to :
- include back `download` key in `module.json`
- include main file during CICD to be part of the released `module.zip` file.

Thanks again @Psyga315 for the report !
